# Generated by Django 4.1.1 on 2024-05-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalskill',
            name='percent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.IntegerField(),
        ),
    ]
