# Generated by Django 4.1.1 on 2024-05-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_professionalskill_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='personal_skill',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='professional_skill',
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.ManyToManyField(blank=True, null=True, to='user_management.education'),
        ),
        migrations.AddField(
            model_name='profile',
            name='personal_skill',
            field=models.ManyToManyField(blank=True, null=True, to='user_management.personalskill'),
        ),
        migrations.AddField(
            model_name='profile',
            name='professional_skill',
            field=models.ManyToManyField(blank=True, null=True, to='user_management.professionalskill'),
        ),
    ]
