# Generated by Django 4.1.1 on 2024-05-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_remove_profile_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.ManyToManyField(blank=True, to='user_management.education'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_skill',
            field=models.ManyToManyField(blank=True, to='user_management.personalskill'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='professional_skill',
            field=models.ManyToManyField(blank=True, to='user_management.professionalskill'),
        ),
    ]
