# Generated by Django 4.1.1 on 2024-06-11 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('подписан', 'подписан'), ('не подписан', 'не подписан')], default='не подписан', max_length=20),
        ),
        migrations.CreateModel(
            name='DockSignGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_docksign_groups', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.document')),
                ('signed_by', models.ManyToManyField(blank=True, related_name='signed_documents', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='docksign_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
